/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppSalesIndexRouteImport } from './routes/_app/sales/index'
import { Route as AppReportsIndexRouteImport } from './routes/_app/reports/index'
import { Route as AppProductsIndexRouteImport } from './routes/_app/products/index'
import { Route as AppProductionIndexRouteImport } from './routes/_app/production/index'
import { Route as AppInventoryIndexRouteImport } from './routes/_app/inventory/index'
import { Route as AppSalesNewRouteImport } from './routes/_app/sales/new'
import { Route as AppProductionNewRouteImport } from './routes/_app/production/new'
import { Route as AppSalesIdEditRouteImport } from './routes/_app/sales/$id.edit'
import { Route as AppProductionIdEditRouteImport } from './routes/_app/production/$id.edit'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppSalesIndexRoute = AppSalesIndexRouteImport.update({
  id: '/sales/',
  path: '/sales/',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsIndexRoute = AppReportsIndexRouteImport.update({
  id: '/reports/',
  path: '/reports/',
  getParentRoute: () => AppRoute,
} as any)
const AppProductsIndexRoute = AppProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => AppRoute,
} as any)
const AppProductionIndexRoute = AppProductionIndexRouteImport.update({
  id: '/production/',
  path: '/production/',
  getParentRoute: () => AppRoute,
} as any)
const AppInventoryIndexRoute = AppInventoryIndexRouteImport.update({
  id: '/inventory/',
  path: '/inventory/',
  getParentRoute: () => AppRoute,
} as any)
const AppSalesNewRoute = AppSalesNewRouteImport.update({
  id: '/sales/new',
  path: '/sales/new',
  getParentRoute: () => AppRoute,
} as any)
const AppProductionNewRoute = AppProductionNewRouteImport.update({
  id: '/production/new',
  path: '/production/new',
  getParentRoute: () => AppRoute,
} as any)
const AppSalesIdEditRoute = AppSalesIdEditRouteImport.update({
  id: '/sales/$id/edit',
  path: '/sales/$id/edit',
  getParentRoute: () => AppRoute,
} as any)
const AppProductionIdEditRoute = AppProductionIdEditRouteImport.update({
  id: '/production/$id/edit',
  path: '/production/$id/edit',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof AppDashboardRoute
  '/production/new': typeof AppProductionNewRoute
  '/sales/new': typeof AppSalesNewRoute
  '/inventory/': typeof AppInventoryIndexRoute
  '/production/': typeof AppProductionIndexRoute
  '/products/': typeof AppProductsIndexRoute
  '/reports/': typeof AppReportsIndexRoute
  '/sales/': typeof AppSalesIndexRoute
  '/production/$id/edit': typeof AppProductionIdEditRoute
  '/sales/$id/edit': typeof AppSalesIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof AppDashboardRoute
  '/production/new': typeof AppProductionNewRoute
  '/sales/new': typeof AppSalesNewRoute
  '/inventory': typeof AppInventoryIndexRoute
  '/production': typeof AppProductionIndexRoute
  '/products': typeof AppProductsIndexRoute
  '/reports': typeof AppReportsIndexRoute
  '/sales': typeof AppSalesIndexRoute
  '/production/$id/edit': typeof AppProductionIdEditRoute
  '/sales/$id/edit': typeof AppSalesIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/production/new': typeof AppProductionNewRoute
  '/_app/sales/new': typeof AppSalesNewRoute
  '/_app/inventory/': typeof AppInventoryIndexRoute
  '/_app/production/': typeof AppProductionIndexRoute
  '/_app/products/': typeof AppProductsIndexRoute
  '/_app/reports/': typeof AppReportsIndexRoute
  '/_app/sales/': typeof AppSalesIndexRoute
  '/_app/production/$id/edit': typeof AppProductionIdEditRoute
  '/_app/sales/$id/edit': typeof AppSalesIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/dashboard'
    | '/production/new'
    | '/sales/new'
    | '/inventory/'
    | '/production/'
    | '/products/'
    | '/reports/'
    | '/sales/'
    | '/production/$id/edit'
    | '/sales/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/dashboard'
    | '/production/new'
    | '/sales/new'
    | '/inventory'
    | '/production'
    | '/products'
    | '/reports'
    | '/sales'
    | '/production/$id/edit'
    | '/sales/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/_app/dashboard'
    | '/_app/production/new'
    | '/_app/sales/new'
    | '/_app/inventory/'
    | '/_app/production/'
    | '/_app/products/'
    | '/_app/reports/'
    | '/_app/sales/'
    | '/_app/production/$id/edit'
    | '/_app/sales/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sales/': {
      id: '/_app/sales/'
      path: '/sales'
      fullPath: '/sales/'
      preLoaderRoute: typeof AppSalesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports/': {
      id: '/_app/reports/'
      path: '/reports'
      fullPath: '/reports/'
      preLoaderRoute: typeof AppReportsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/products/': {
      id: '/_app/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof AppProductsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/production/': {
      id: '/_app/production/'
      path: '/production'
      fullPath: '/production/'
      preLoaderRoute: typeof AppProductionIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/inventory/': {
      id: '/_app/inventory/'
      path: '/inventory'
      fullPath: '/inventory/'
      preLoaderRoute: typeof AppInventoryIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sales/new': {
      id: '/_app/sales/new'
      path: '/sales/new'
      fullPath: '/sales/new'
      preLoaderRoute: typeof AppSalesNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/production/new': {
      id: '/_app/production/new'
      path: '/production/new'
      fullPath: '/production/new'
      preLoaderRoute: typeof AppProductionNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sales/$id/edit': {
      id: '/_app/sales/$id/edit'
      path: '/sales/$id/edit'
      fullPath: '/sales/$id/edit'
      preLoaderRoute: typeof AppSalesIdEditRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/production/$id/edit': {
      id: '/_app/production/$id/edit'
      path: '/production/$id/edit'
      fullPath: '/production/$id/edit'
      preLoaderRoute: typeof AppProductionIdEditRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppDashboardRoute: typeof AppDashboardRoute
  AppProductionNewRoute: typeof AppProductionNewRoute
  AppSalesNewRoute: typeof AppSalesNewRoute
  AppInventoryIndexRoute: typeof AppInventoryIndexRoute
  AppProductionIndexRoute: typeof AppProductionIndexRoute
  AppProductsIndexRoute: typeof AppProductsIndexRoute
  AppReportsIndexRoute: typeof AppReportsIndexRoute
  AppSalesIndexRoute: typeof AppSalesIndexRoute
  AppProductionIdEditRoute: typeof AppProductionIdEditRoute
  AppSalesIdEditRoute: typeof AppSalesIdEditRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppDashboardRoute: AppDashboardRoute,
  AppProductionNewRoute: AppProductionNewRoute,
  AppSalesNewRoute: AppSalesNewRoute,
  AppInventoryIndexRoute: AppInventoryIndexRoute,
  AppProductionIndexRoute: AppProductionIndexRoute,
  AppProductsIndexRoute: AppProductsIndexRoute,
  AppReportsIndexRoute: AppReportsIndexRoute,
  AppSalesIndexRoute: AppSalesIndexRoute,
  AppProductionIdEditRoute: AppProductionIdEditRoute,
  AppSalesIdEditRoute: AppSalesIdEditRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
